# Name of your application. Used to uniquely configure containers.
service: my-app

# SSH
ssh:
  user: root
  host: 192.168.0.1
  port: 22

servers:
  - 192.168.0.1

# Docker
registry:
  image: user/my-app
  server: registry.digitalocean.com
  username: docker_username
  password: docker_password
  reponame: target_repo_name

env:
  DATABASE_URL: YOUR_DATABASE_URL
